#!/usr/bin/env bash
#
# copy.sh — install/update the gdscript-linter addon into another Godot project.
#
# Usage:
#   ./copy.sh <godot-project-dir>
#
# Copies this repo's addons/gdscript-linter/ into <godot-project-dir>/addons/gdscript-linter/
# as a clean, fresh install (stale files inside the destination addon are removed).
# Safe to re-run. Fixes the trailing-slash mistake that dumps files loose into addons/.
#
# Also drops a lint.sh in the target project root that runs the linter over that
# project (see LINT_SCRIPT_NAME below). Set NO_LINT_SCRIPT=1 to skip it.

set -euo pipefail

# Resolve the source addon relative to THIS script, so cwd doesn't matter.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$SCRIPT_DIR/addons/gdscript-linter"
ADDON_NAME="gdscript-linter"
LINT_SCRIPT_NAME="lint.sh"
# Marker in the generated lint script. We only ever overwrite a file carrying it,
# so a hand-written lint.sh in the target project is never clobbered.
LINT_MARKER="# generated-by: gdscript-linter copy.sh"

die() { echo "error: $*" >&2; exit 1; }

[ $# -eq 1 ] || die "usage: $0 <godot-project-dir>"
TARGET_PROJECT="${1%/}"   # strip trailing slash

[ -d "$SRC" ] || die "source addon not found: $SRC"
[ -d "$TARGET_PROJECT" ] || die "not a directory: $TARGET_PROJECT"
if [ ! -f "$TARGET_PROJECT/project.godot" ]; then
	echo "warning: no project.godot in $TARGET_PROJECT — is this the project root?" >&2
fi

ADDONS_DIR="$TARGET_PROJECT/addons"
DEST="$ADDONS_DIR/$ADDON_NAME"
mkdir -p "$DEST"

# Warn about a previous loose copy (addon files sitting directly in addons/ rather
# than in addons/gdscript-linter/). Duplicate class_name declarations there cause
# "hides a global script class" compile errors. We do NOT auto-delete — those files
# live in your project and might collide with other addons; remove them by hand.
STRAY=()
for entry in "$SRC"/*; do
	name="$(basename "$entry")"
	[ "$name" = "$ADDON_NAME" ] && continue
	if [ -e "$ADDONS_DIR/$name" ]; then
		STRAY+=("$ADDONS_DIR/$name")
	fi
done
if [ "${#STRAY[@]}" -gt 0 ]; then
	echo "warning: found addon files loose in $ADDONS_DIR/ (likely a bad earlier copy):" >&2
	printf '  %s\n' "${STRAY[@]}" >&2
	echo "  these duplicate the class_name declarations — remove them before running Godot." >&2
fi

# Fresh sync into the destination addon folder only.
if command -v rsync >/dev/null 2>&1; then
	rsync -a --delete "$SRC/" "$DEST/"
else
	rm -rf "$DEST"
	mkdir -p "$DEST"
	cp -R "$SRC/." "$DEST/"
fi

# Stamp the install with the current time. rsync -a preserves the SOURCE mtimes,
# so freshly copied files can look older than the target's script class cache —
# lint.sh compares against this stamp to decide whether to re-import.
touch "$DEST/.installed-at"

echo "copied $ADDON_NAME -> $DEST"

# ---------------------------------------------------------------------------
# Generate <target>/lint.sh — a thin wrapper that runs the linter over the
# target project. It locates a Godot binary at run time (see find_godot below)
# and forwards all its arguments to the analyzer CLI.
# ---------------------------------------------------------------------------
if [ "${NO_LINT_SCRIPT:-0}" = "1" ]; then
	exit 0
fi

LINT_SCRIPT="$TARGET_PROJECT/$LINT_SCRIPT_NAME"
if [ -e "$LINT_SCRIPT" ] && ! grep -qF "$LINT_MARKER" "$LINT_SCRIPT" 2>/dev/null; then
	echo "warning: $LINT_SCRIPT exists and was not generated by copy.sh — left untouched" >&2
	exit 0
fi

# The installer path is baked in here, at copy time, because the target project
# has no other way to find the linter repository it was installed from. The
# generated script falls back to searching if this path stops existing.
cat > "$LINT_SCRIPT" <<PRELUDE_EOF
#!/usr/bin/env bash
# generated-by: gdscript-linter copy.sh — regenerated on every copy, don't edit.
INSTALL_FORMATTER="$SCRIPT_DIR/scripts/install-formatter.sh"
PRELUDE_EOF

cat >> "$LINT_SCRIPT" <<'LINT_EOF'
#
# lint.sh — run the GDScript linter over this project.
#
# Usage:
#   ./lint.sh                       # console report for the whole project
#   ./lint.sh --top 10              # any analyze-cli.gd option
#   ./lint.sh src/ scripts/         # limit to directories
#   ./lint.sh --sarif > out.sarif
#
# Runs with --check-members: every script is loaded, so scripts that fail to
# compile and self.foo.bar accesses that resolve to nothing are reported as
# critical. That is the point of running this before launching the game.
# NO_MEMBER_CHECK=1 skips it.
#
# Also runs with --check-unused-functions, which reports functions nothing in
# the project references. NO_UNUSED_CHECK=1 skips it.
#
# And with --check-exports, which reports object-typed @export vars that nothing
# null-guards. NO_EXPORT_CHECK=1 skips it.
#
# Some checks need structure from `gdscript-formatter index`. The wrapper finds
# that binary the same way it finds Godot. Set GDLINT_FORMATTER to pin one.
#
# Set GODOT=/path/to/godot to pin a specific binary.
#
# Exit codes: 0 = clean, 1 = warnings, 2 = critical issues, 3 = could not run
# (no Godot, no formatter for the index-backed checks, or a failed import).

set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANALYZER="res://addons/gdscript-linter/analyzer/analyze-cli.gd"

find_godot() {
	if [ -n "${GODOT:-}" ]; then
		printf '%s\n' "$GODOT"
		return 0
	fi
	local candidate
	# godot-mono/godot4-mono are what the Homebrew casks put on PATH.
	for candidate in godot godot4 godot-mono godot4-mono Godot; do
		if command -v "$candidate" >/dev/null 2>&1; then
			command -v "$candidate"
			return 0
		fi
	done
	# macOS app bundles, which are not on PATH by default.
	for candidate in \
		"/Applications/Godot.app/Contents/MacOS/Godot" \
		"$HOME/Applications/Godot.app/Contents/MacOS/Godot" \
		"/Applications/Godot_mono.app/Contents/MacOS/Godot" \
		"$HOME/Applications/Godot_mono.app/Contents/MacOS/Godot"; do
		if [ -x "$candidate" ]; then
			printf '%s\n' "$candidate"
			return 0
		fi
	done
	return 1
}

if ! GODOT_BIN="$(find_godot)"; then
	echo "error: no Godot binary found — put 'godot' on PATH or set GODOT=/path/to/godot" >&2
	exit 127
fi

# Three of the checks read source structure from `gdscript-formatter index`, so
# the linter and that binary are one system. The linter repository owns the
# script that builds it and answers where it is; this asks, rather than guessing
# at paths that drift. Building on every run is what keeps the two sides in step,
# and an up-to-date build costs a fraction of a second.
#
# Only asked for when a check that needs it is actually going to run, so
# NO_MEMBER_CHECK=1 NO_UNUSED_CHECK=1 NO_EXPORT_CHECK=1 ./lint.sh still works
# with no formatter present at all.
needs_formatter=0
if [ "${NO_MEMBER_CHECK:-0}" != "1" ] \
	|| [ "${NO_UNUSED_CHECK:-0}" != "1" ] \
	|| [ "${NO_EXPORT_CHECK:-0}" != "1" ]; then
	needs_formatter=1
fi
case " $* " in
	*" --check-members "*|*" --check-unused-functions "*|*" --check-exports "*)
		needs_formatter=1 ;;
esac

if [ "$needs_formatter" = "1" ]; then
	if [ -x "${INSTALL_FORMATTER:-}" ]; then
		if FORMATTER_BIN="$("$INSTALL_FORMATTER")"; then
			export GDLINT_FORMATTER="$FORMATTER_BIN"
		else
			# Exit 3, not the installer's own code: this script's contract is
			# 0 clean / 1 warnings / 2 critical / 3 could not run, and reporting
			# a missing formatter as 2 would read as "critical issues found".
			echo "lint.sh: $INSTALL_FORMATTER failed (see above); cannot run the checks that need it" >&2
			exit 3
		fi
	elif [ -z "${GDLINT_FORMATTER:-}" ] && command -v gdscript-formatter >/dev/null 2>&1; then
		# The linter repository has moved or gone since this script was written.
		export GDLINT_FORMATTER="$(command -v gdscript-formatter)"
		echo "lint.sh: ${INSTALL_FORMATTER:-installer} is missing; using gdscript-formatter from PATH" >&2
	elif [ -z "${GDLINT_FORMATTER:-}" ]; then
		# Say so here rather than letting the analyzer fail halfway in with a
		# message about GDLINT_FORMATTER that never mentions the actual remedy.
		echo "error: the checks that read source structure cannot run: no formatter anywhere." >&2
		echo "  This script was generated by copy.sh and looks for the installer at:" >&2
		echo "    ${INSTALL_FORMATTER:-<installer path was not baked in>}" >&2
		echo "  which no longer exists, and gdscript-formatter is not on PATH either." >&2
		echo "  Fix it with any one of:" >&2
		echo "    - re-run copy.sh from the gdscript-linter repository (regenerates this script)" >&2
		echo "    - cargo install --path <GDScript-formatter checkout>  (puts it on PATH)" >&2
		echo "    - set GDLINT_FORMATTER=/path/to/gdscript-formatter" >&2
		echo "    - re-run with NO_MEMBER_CHECK=1 NO_UNUSED_CHECK=1 NO_EXPORT_CHECK=1" >&2
		exit 3
	fi
fi

ADDON_DIR="$PROJECT_DIR/addons/gdscript-linter"
if [ ! -f "$ADDON_DIR/analyzer/analyze-cli.gd" ]; then
	echo "error: gdscript-linter addon not found in $PROJECT_DIR/addons/" >&2
	exit 1
fi

# The analyzer's checkers are `class_name` globals, which only resolve once Godot
# has imported the project into .godot/global_script_class_cache.cfg. Without a
# fresh cache every checker fails with "Identifier ... not declared". Re-import
# when the cache is missing or older than any addon script (i.e. after a copy).
CLASS_CACHE="$PROJECT_DIR/.godot/global_script_class_cache.cfg"
needs_import=0
if [ ! -f "$CLASS_CACHE" ]; then
	needs_import=1
elif [ "$ADDON_DIR/.installed-at" -nt "$CLASS_CACHE" ]; then
	needs_import=1  # addon was (re)copied since the last import
elif [ -n "$(find "$ADDON_DIR" -name '*.gd' -newer "$CLASS_CACHE" -print -quit)" ]; then
	needs_import=1  # addon scripts edited in place
fi
if [ "$needs_import" = "1" ]; then
	echo "lint.sh: importing project (refreshing script class cache)..." >&2
	# The exit code is not evidence: --import exits non-zero whenever any script
	# in the project fails to compile, which is normal mid-development, and the
	# cache is still written for everything else. What matters is whether the
	# cache exists afterwards. Without it not a single class_name resolves, the
	# analyzer fails to load, Godot exits 0 anyway, and this script would report
	# a clean run that checked nothing at all.
	IMPORT_LOG="$("$GODOT_BIN" --headless --path "$PROJECT_DIR" --import 2>&1)" || true
	if [ ! -f "$CLASS_CACHE" ]; then
		echo "error: the import produced no script class cache at $CLASS_CACHE" >&2
		echo "  the linter's checkers are class_name globals and cannot run without it," >&2
		echo "  so the run would report nothing while looking clean. Fix the import" >&2
		echo "  (check the Godot binary and the project) and re-run. Import output:" >&2
		if [ -n "$IMPORT_LOG" ]; then
			printf '%s\n' "$IMPORT_LOG" >&2
		else
			echo "  (empty: is GODOT=$GODOT_BIN actually a Godot 4 binary?)" >&2
		fi
		exit 3
	fi
	case "$IMPORT_LOG" in
		*"SCRIPT ERROR"*)
			echo "warning: the import step reported script errors; classes may be missing from the cache" >&2
			printf '%s\n' "$IMPORT_LOG" >&2 ;;
	esac
fi

# Default to --clickable. The analyzer's `console` format only lists critical,
# long-function, pinned and TODO issues — a project whose issues are all e.g.
# print-statements gets a summary count and nothing else. --clickable lists every
# issue as file:line. Pass any explicit format (including --format console) to
# override this.
has_format=0
for arg in "$@"; do
	case "$arg" in
		--format|--json|--sarif|--clickable|--html|--github) has_format=1; break ;;
	esac
done
if [ "$has_format" = "0" ]; then
	set -- --clickable "$@"
fi

# Member checking by default -- this script exists to be run before launching the
# game, and a script that will not compile is what is most worth knowing then.
if [ "${NO_MEMBER_CHECK:-0}" != "1" ]; then
	case " $* " in
		*" --check-members "*) ;;
		*) set -- --check-members "$@" ;;
	esac
fi

# Dead-function reporting by default. Not a launch blocker (it is a warning), but
# it is the kind of rot that only shows up if something looks for it.
if [ "${NO_UNUSED_CHECK:-0}" != "1" ]; then
	case " $* " in
		*" --check-unused-functions "*) ;;
		*) set -- --check-unused-functions "$@" ;;
	esac
fi

# Unguarded @export references by default -- an export nobody wired is null, and
# that only shows up once the scene runs.
if [ "${NO_EXPORT_CHECK:-0}" != "1" ]; then
	case " $* " in
		*" --check-exports "*) ;;
		*) set -- --check-exports "$@" ;;
	esac
fi

# --path makes the run independent of the caller's cwd; everything after --
# belongs to the analyzer.
"$GODOT_BIN" --headless --path "$PROJECT_DIR" --script "$ANALYZER" -- "$@"
LINT_EOF

chmod +x "$LINT_SCRIPT"
echo "wrote lint script -> $LINT_SCRIPT"
